import type { Metadata } from "next";
import { cookies } from "next/headers";

import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,

} from "@/components/ui/sidebar";

import { AppSidebar } from "@/components/app-sidebar";
import { Header } from "@/components/header";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-ibm-plex-sans",
  weight: "400",
});
const ibmPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.variable} ${ibmPlexMono.variable} antialiased`}
      >
        <SidebarProvider defaultOpen={defaultOpen}>
          <AppSidebar />
          <main className="w-full">
            <SidebarInset>
             <Header />
              <main className="p-4 font-sans bg-gray-100 min-h-screen">
                {children}
              </main>
            </SidebarInset>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
